### ISSUE TITLE
Add documentation for QueryBus

### ISSUE THREAD

**Issue by fmasa** [egendev/message-bus#7]

**Comment by JanMikes** [comment]
Yeah please, im curious 😃

**Comment by fmasa** [comment]
It's very similar to usage of command bus. The only difference is that handler returns result and that it's registered with `queryBus.handler` tag.

```yaml
messageBus:
    queryBus:

services:
    - class: MyCoolHandler
      tags: [queryBus.handler]
```

```php

class MyCoolQuery {}

class MyCoolQueryHandler
{
    public function handle(MyCoolQuery $query): string
    {
        return 'foo';
    }
}

/** @var eGen\MessageBus\Bus\QueryBus() $queryBus */
$result = $queryBus->handle(new MyCoolQuery());

// prints "foo"
print_r($result);
```
